# Generated by Django 4.0.4 on 2022-06-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Injection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='Ссылка')),
                ('xss', models.TextField(verbose_name='Результат XSS')),
                ('sql', models.TextField(verbose_name='Результат SQL Injection')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(verbose_name='Слово')),
                ('count', models.IntegerField(verbose_name='Количество слов')),
            ],
            options={
                'verbose_name': 'Счетчик слово',
                'verbose_name_plural': 'Счетчики слов',
            },
        ),
        migrations.CreateModel(
            name='PageAnalyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='url')),
                ('title', models.TextField(verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание')),
                ('headings', models.TextField(verbose_name='Информация о тегах h1-h6')),
            ],
        ),
        migrations.CreateModel(
            name='SeoWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Предупреждение сео',
                'verbose_name_plural': 'Предупреждения сео',
            },
        ),
        migrations.CreateModel(
            name='SeoAnalyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.ManyToManyField(blank=True, to='metadata.keyword', verbose_name='Информация о всех словах')),
                ('pages', models.ManyToManyField(blank=True, to='metadata.pageanalyze', verbose_name='Информация о сео на всех страницах')),
            ],
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitemap', models.TextField(verbose_name='Проверка sitemap')),
                ('robots', models.TextField(verbose_name='Проверка robots')),
                ('urls', models.TextField(verbose_name='Внешние ссылки')),
                ('seoanalyze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.seoanalyze', verbose_name='Сканирование SEO')),
            ],
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='Ссылка')),
                ('injections', models.ManyToManyField(to='metadata.injection', verbose_name='Результаты сканирования инъекций')),
                ('seo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.seo', verbose_name='Результаты сео сканирования')),
            ],
        ),
        migrations.AddField(
            model_name='pageanalyze',
            name='seowarnings',
            field=models.ManyToManyField(to='metadata.seowarning', verbose_name='СЕО ошибки'),
        ),
    ]
