# Generated by Django 4.0.4 on 2022-06-04 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='injection',
            options={'verbose_name': 'Результаты сканирования инъекций на странице', 'verbose_name_plural': 'Результаты сканирования инъекций на страницах'},
        ),
        migrations.AlterModelOptions(
            name='pageanalyze',
            options={'verbose_name': 'Информация о странице', 'verbose_name_plural': 'Информация о страницах'},
        ),
        migrations.AlterModelOptions(
            name='scanner',
            options={'verbose_name': 'Результат сканирования', 'verbose_name_plural': 'Результаты сканирования'},
        ),
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'Результат СЕО сканирования', 'verbose_name_plural': 'Результаты СЕО сканирования'},
        ),
        migrations.AlterModelOptions(
            name='seoanalyze',
            options={'verbose_name': 'Результат СЕО сканирования страниц', 'verbose_name_plural': 'Результаты СЕО сканирования страницы'},
        ),
        migrations.AlterModelOptions(
            name='seowarning',
            options={'verbose_name': 'Предупреждение СЕО', 'verbose_name_plural': 'Предупреждения СЕО'},
        ),
        migrations.AlterField(
            model_name='scanner',
            name='seo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.seo', verbose_name='Результаты сео сканирования'),
        ),
    ]
