# Generated by Django 4.0.4 on 2022-06-04 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_alter_injection_options_alter_pageanalyze_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='seoanalyze',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.seoanalyze', verbose_name='Сканирование SEO'),
        ),
    ]
