# Generated by Django 4.0.4 on 2022-06-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_port_host_scanner_hosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BruteForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh', models.TextField(null=True, verbose_name='ssh')),
                ('ftp', models.TextField(null=True, verbose_name='ftp')),
                ('mysql', models.TextField(null=True, verbose_name='mysql')),
                ('mysqlempty', models.TextField(null=True, verbose_name='mysql empty')),
            ],
        ),
        migrations.AddField(
            model_name='port',
            name='cve',
            field=models.TextField(null=True, verbose_name='CVE'),
        ),
        migrations.AddField(
            model_name='scanner',
            name='auth',
            field=models.TextField(null=True, verbose_name='Результаты сканирование аутентификации'),
        ),
        migrations.AddField(
            model_name='scanner',
            name='httpenum',
            field=models.TextField(null=True, verbose_name='Результаты сканирование файловой системы'),
        ),
        migrations.AddField(
            model_name='scanner',
            name='bruteforce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.bruteforce', verbose_name='Результаты подбора логинов и паролей для хостов'),
        ),
    ]
