# Generated by Django 4.0.4 on 2022-06-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_bruteforce_port_cve_scanner_auth_scanner_httpenum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seo',
            name='seoanalyze',
        ),
        migrations.AlterField(
            model_name='injection',
            name='sql',
            field=models.BooleanField(verbose_name='Результат SQL Injection'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='xss',
            field=models.BooleanField(verbose_name='Результат XSS'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='robots',
            field=models.BooleanField(verbose_name='Проверка robots'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='sitemap',
            field=models.BooleanField(verbose_name='Проверка sitemap'),
        ),
    ]
