# Generated by Django 4.0.4 on 2022-06-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_urlstatus_remove_seo_urls_seo_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlstatus',
            name='status',
            field=models.TextField(verbose_name='Статус'),
        ),
    ]
