# Generated by Django 4.0.4 on 2022-06-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_alter_urlstatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Тег title')),
                ('url', models.TextField(verbose_name='URL')),
            ],
        ),
        migrations.AddField(
            model_name='seo',
            name='tags',
            field=models.ManyToManyField(to='metadata.tagstatus', verbose_name='Наличие тегов'),
        ),
    ]
