# Generated by Django 4.0.4 on 2022-06-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_alter_tagstatus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagstatus',
            name='description',
            field=models.BooleanField(null=True, verbose_name='Тег description'),
        ),
        migrations.AddField(
            model_name='tagstatus',
            name='keywords',
            field=models.BooleanField(null=True, verbose_name='Тег keywords'),
        ),
        migrations.AlterField(
            model_name='tagstatus',
            name='title',
            field=models.BooleanField(null=True, verbose_name='Тег title'),
        ),
    ]
