# Generated by Django 4.0.4 on 2022-06-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_remove_seo_tags_urlstatus_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Httpenum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(verbose_name='Название продукта')),
                ('ostype', models.TextField(null=True, verbose_name='Тип ОС')),
                ('version', models.TextField(null=True, verbose_name='Версия')),
                ('extrainfo', models.TextField(null=True, verbose_name='Дополнительная информация')),
                ('hostname', models.TextField(null=True, verbose_name='Имя хоста')),
                ('httpenum', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='httpenum',
        ),
        migrations.AddField(
            model_name='scanner',
            name='httpenum',
            field=models.ManyToManyField(to='metadata.httpenum', verbose_name='Результаты сканирование конфигурации'),
        ),
    ]
