# Generated by Django 4.0.4 on 2022-06-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_httpenum_remove_scanner_httpenum_scanner_httpenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authfinder', models.TextField(verbose_name='Формы авторизации')),
                ('authbrute', models.TextField(verbose_name='Результаты bruteforce')),
            ],
        ),
        migrations.AlterField(
            model_name='scanner',
            name='auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.auth', verbose_name='Результаты сканирование аутентификации'),
        ),
    ]
